name: Test Livehead

on:
  push:
    branches:
      - main

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          test -f src/_cli_version.py
          echo "ok=true"
